// Product content, not a copy of the previous site. All page text is rendered
// into static HTML for search, accessibility, and browsers without JavaScript.
export const stores = {
  ios: 'https://apps.apple.com/us/app/arenetto/id6791795300',
  android: 'https://play.google.com/store/apps/details?id=com.tomasarenas.arenetto',
};

export const social = [
  { name: 'Instagram', url: 'https://www.instagram.com/arenetto.accordion/' },
  { name: 'TikTok', url: 'https://www.tiktok.com/@arenetto.accordion' },
  { name: 'YouTube', url: 'https://www.youtube.com/@arenettoapp' },
  { name: 'Facebook', url: 'https://www.facebook.com/p/Arenetto-Accordion-61591586806487/' },
];

export const performances = [
  { id: 'k02WsCjudA4', title: 'Siempre te voy a querer', genre: 'Norteño', image: 'session-norteno.jpg', width:405, height:720, creator: 'Arenetto Accordion' },
  { id: 'i9teGjhY3Ak', title: 'Osito Dormilón', genre: 'Vallenato', image: 'session-vallenato.jpg', width:480, height:360, creator: 'Arenetto Accordion' },
  { id: 'qBVwqO7cG_w', title: 'Desvelado', genre: 'Norteño', image: 'session-desvelado.jpg', width:480, height:360, creator: 'Arenetto Accordion' },
];

// Exact short excerpts. No composite quotations, invented names, or owner
// self-reviews. Translations are identified separately from the originals.
export const reviews = [
  {
    id: '14559002437', author: 'soffiaaaaa_', title: 'Aprendiendo🙂', rating: 5,
    quote: 'los videos de ig me han ayudado para aprender',
    translation: 'The Instagram videos have helped me learn.',
    date: '2026-09-16', store: 'App Store', country: 'MX', language: 'es',
    source: 'https://itunes.apple.com/mx/rss/customerreviews/id=6791795300/sortby=mostrecent/json',
    url: 'https://apps.apple.com/mx/app/arenetto/id6791795300?see-all=reviews',
  },
  {
    id: '14528112903', author: 'Emilianodlrs', title: 'Está chido', rating: 5,
    quote: 'No pagas nada y tienes todos los sonidos que se escuchan igual',
    translation: 'You pay nothing and get all the sounds, which sound the same.',
    date: '2026-09-08', store: 'App Store', country: 'MX', language: 'es',
    source: 'https://itunes.apple.com/mx/rss/customerreviews/id=6791795300/sortby=mostrecent/json',
    url: 'https://apps.apple.com/mx/app/arenetto/id6791795300?see-all=reviews',
  },
  {
    id: '1ea280c9-bdaf-477d-8ade-91f86e9a7de4', author: 'Juan Alvarado', rating: 5,
    quote: 'Excelente motor de sonido y muy buena respuesta.',
    translation: 'Excellent sound engine and great responsiveness.',
    date: '2026-08-18', store: 'Google Play', language: 'es', verifiedOn: '2026-10-04',
    source: 'https://play.google.com/store/apps/details?id=com.tomasarenas.arenetto&hl=es_419&gl=MX',
    url: 'https://play.google.com/store/apps/details?id=com.tomasarenas.arenetto&hl=es_419&gl=MX',
  },
  {
    id: 'd425665d-0fda-4723-8d2b-a52504578a3f', author: 'Maximiliano López', rating: 5,
    quote: 'es perfecta sigan asi',
    translation: 'It’s perfect. Keep it up!',
    date: '2026-08-24', store: 'Google Play', language: 'es', verifiedOn: '2026-10-04',
    source: 'https://play.google.com/store/apps/details?id=com.tomasarenas.arenetto&hl=es_419&gl=MX',
    url: 'https://play.google.com/store/apps/details?id=com.tomasarenas.arenetto&hl=es_419&gl=MX',
  },
];

export const copy = {
  en: {
    lang: 'en', path: '/', other: '/es/', otherLabel: 'Español',
    title: 'Arenetto — Your accordion. Anywhere.',
    description: 'Play Norteño and Vallenato on your phone or tablet. A premium diatonic accordion with 28, 31 or 34 buttons, tunings and push/pull control. Free. No ads.',
    skip: 'Skip to content', navLabel: 'Main navigation', nav: ['The instrument', 'In the hands of players', 'Questions'], menu: 'Open navigation', download: 'Get Arenetto',
    eyebrow: 'THE DIATONIC ACCORDION, REIMAGINED',
    hero: ['Your accordion.', 'Anywhere.'],
    intro: 'The sounds you love. An instrument that goes with you. Play Norteño and Vallenato on your phone or tablet.',
    free: 'Free to play. No ads. No account.',
    hear: 'See & hear it', heroAlt: 'The Arenetto accordion with pearl buttons, gold grille and five Norteño registers',
    heroCaption: 'A real app capture. An instrument made to be played.',
    proof: ['28 / 31 / 34', 'Button layouts', 'Norteño + Vallenato', 'Two musical traditions', 'Push & pull', 'Your expression, your direction'],
    instrumentEye: 'FAMILIAR SOUND. A NEW WAY TO PLAY.', instrumentTitle: ['Two traditions.', 'One instrument.'],
    instrumentIntro: 'Find the character of your music, from a Norteño melody to a Vallenato phrase.',
    familyLabel: 'Choose a sound family',
    norteno: { title: 'Norteño', text: 'Five registers. One unmistakable character. Switch between Bassoon, Bandoneon, Master, Violin and Clarinet while you play.', features: ['Five live registers', 'G–C–F · F–B♭–E♭ · E–A–D'], demo: 'Hear Norteño', alt: 'Arenetto Norteño instrument with five rocker registers', caption: '34 buttons · Norteño · Master register' },
    vallenato: { title: 'Vallenato', text: 'Brillante or Armonizado. Choose your sound and let the melody lead, with a clean cabinet designed for Vallenato.', features: ['Brillante + Armonizado', 'A–D–G · G–C–F · and more'], demo: 'Hear Vallenato', alt: 'Arenetto Vallenato instrument with its uninterrupted central cabinet', caption: '31 buttons · Vallenato' },
    playingEye: 'LESS SETUP. MORE MUSIC.', playingTitle: ['Pick it up.', 'Make it yours.'],
    playing: [
      { title: 'Play notes. Hold chords.', text: 'Use several fingers at once. Move through a melody or hold a chord as you change direction.' },
      { title: 'Push. Pull. Express.', text: 'Change bellows direction to play the other set of notes, as on a diatonic accordion.' },
      { title: 'Find your familiar layout.', text: 'Choose 28, 31 or 34 buttons and your tuning. Keep note labels on when you want a visual reference.' },
    ],
    tabletEye: 'MORE ROOM TO FIND YOUR RHYTHM.', tabletTitle: ['Pocket-sized.', 'Or a little bigger.'],
    tabletText: 'Large, screen-filling buttons on phones. On iPad and Android tablets, choose button size and spacing independently to suit your playing style.',
    tabletAlt: 'Arenetto on iPad, with a larger keyboard surface and the full black-and-gold cabinet', tabletCaption: 'Phone & tablet. The same Arenetto identity.',
    labels: 'Optional note labels', layouts: '28, 31 & 34 buttons', tabletPresets: 'Tablet size & spacing presets',
    sessionsEye: 'THE MUSIC SPEAKS FOR ITSELF.', sessionsTitle: ['Not just a screenshot.', 'A song waiting to happen.'],
    sessionsText: 'Real performances from Arenetto Accordion. Pick a session, turn up the sound, and hear the instrument in action.',
    playVideo: 'Watch', youtube: 'Watch on YouTube', socialInvite: 'Playing something you love? Share it with #arenetto.', socialHeading: 'Follow the music',
    reviewEye: 'WORDS FROM THE PEOPLE PLAYING.', reviewTitle: ['Small screen.', 'Real connection.'],
    reviewText: 'A few words from Arenetto players on the App Store and Google Play.', original: 'Original Spanish excerpt', translated: 'Translated from Spanish', reviewSource: 'Read the original review', reviewDisclaimer: 'Selected excerpts from App Store and Google Play reviews. English translations of Spanish originals. Individual experiences, not a guarantee.',
    privacyTitle: 'Just you and the music.', privacyItems: [['No ads', 'Nothing to sell you while you play.'], ['No account', 'Open the app and start playing.'], ['Your settings stay yours', 'Saved on your device. No app tracking.']],
    faqEye: 'A FEW THINGS WORTH KNOWING.', faqTitle: 'Before your first note.',
    faq: [
      ['Is Arenetto free?', 'Yes. Arenetto is free on the App Store and Google Play, with no ads, subscriptions or in-app purchases.'],
      ['Where can I play it?', 'On iPhone and iPad, and on Android phones and tablets. The instrument is designed to be played in landscape. Check your store listing for current device compatibility.'],
      ['What is push/pull control?', 'A diatonic accordion plays different notes depending on bellows direction. Arenetto lets you select push or pull while playing the buttons.'],
      ['Can I choose my layout and tuning?', 'Yes. Choose 28, 31 or 34 buttons, select your sound family and tuning, and show note labels with sharps or flats if you prefer. Tablets also have button-size and spacing presets.'],
      ['Do I need to create an account?', 'No. There is no sign-up. Instrument preferences are saved locally on your device.'],
      ['Is it available in Spanish?', 'Yes. The app and this website are available in English and Spanish.'],
    ],
    help: 'Need a hand?', contact: 'We’re here to help.',
    closingEye: 'YOUR NEXT MELODY IS WAITING.', closingTitle: ['Less scrolling.', 'More playing.'], closingText: 'Your accordion is one download away.',
    footerDescription: 'A diatonic accordion. A little closer to the music.', footerNav: 'Footer navigation', footerLinks: ['Privacy', 'Terms', 'Support'],
    iosLabel: 'Download Arenetto on the App Store', androidLabel: 'Get Arenetto on Google Play',
    dialogClose: 'Close video', dialogNotice: 'The video loads from YouTube only after you choose to watch. YouTube’s own privacy policy applies.', videoError: 'Cannot load the player? Watch this session directly on YouTube.',
    downloadTitle: 'Your next note starts here.', downloadText: 'Choose your store and open Arenetto on your phone or tablet.', downloadEmbedded: 'If your social app won’t open the store, use its menu to open this page in your browser.', androidStatus: 'Available on Google Play.',
    pageNames: {privacy: 'Privacy', terms: 'Terms', support: 'Support'}, notFound: 'A little off-key.', notFoundText: 'This page isn’t here. Let’s get you back to the music.', home: 'Back to Arenetto',
  },
  es: {
    lang: 'es', path: '/es/', other: '/', otherLabel: 'English',
    title: 'Arenetto — Tu acordeón. Donde quieras.',
    description: 'Toca norteño y vallenato en tu teléfono o tablet. Un acordeón diatónico con 28, 31 o 34 botones, afinaciones y control de fuelle. Gratis y sin anuncios.',
    skip: 'Saltar al contenido', navLabel: 'Navegación principal', nav: ['El instrumento', 'En manos de quienes tocan', 'Preguntas'], menu: 'Abrir navegación', download: 'Descarga Arenetto',
    eyebrow: 'EL ACORDEÓN DIATÓNICO, REIMAGINADO',
    hero: ['Tu acordeón.', 'Donde quieras.'],
    intro: 'Los sonidos que te gustan. Un instrumento que va contigo. Toca norteño y vallenato en tu teléfono o tablet.',
    free: 'Gratis. Sin anuncios. Sin crear una cuenta.',
    hear: 'Mira cómo suena', heroAlt: 'El acordeón Arenetto con botones de nácar, rejilla dorada y cinco registros de norteño',
    heroCaption: 'Una captura real de la app. Un instrumento hecho para tocar.',
    proof: ['28 / 31 / 34', 'Distribuciones de botones', 'Norteño + Vallenato', 'Dos tradiciones musicales', 'Abrir y cerrar', 'Tu expresión, tu dirección'],
    instrumentEye: 'EL SONIDO DE SIEMPRE. OTRA FORMA DE TOCAR.', instrumentTitle: ['Dos tradiciones.', 'Un instrumento.'],
    instrumentIntro: 'Encuentra el carácter de tu música, desde una melodía norteña hasta un paseo vallenato.',
    familyLabel: 'Elige una familia de sonido',
    norteno: { title: 'Norteño', text: 'Cinco registros. Un carácter inconfundible. Cambia entre Bassoon, Bandoneón, Master, Violín y Clarinete mientras tocas.', features: ['Cinco registros en pantalla', 'G–C–F · F–B♭–E♭ · E–A–D'], demo: 'Escucha norteño', alt: 'El instrumento de norteño de Arenetto con cinco registros mecánicos', caption: '34 botones · Norteño · Registro Master' },
    vallenato: { title: 'Vallenato', text: 'Brillante o Armonizado. Elige tu sonido y deja que la melodía lleve el ritmo, con un diseño limpio hecho para vallenato.', features: ['Brillante + Armonizado', 'A–D–G · G–C–F · y más'], demo: 'Escucha vallenato', alt: 'El instrumento de vallenato de Arenetto con el gabinete central continuo', caption: '31 botones · Vallenato' },
    playingEye: 'MENOS AJUSTES. MÁS MÚSICA.', playingTitle: ['Empieza a tocar.', 'Hazlo tuyo.'],
    playing: [
      { title: 'Toca notas. Forma acordes.', text: 'Usa varios dedos a la vez. Recorre una melodía o mantén un acorde mientras cambias de dirección.' },
      { title: 'Abre. Cierra. Exprésate.', text: 'Cambia la dirección del fuelle para tocar el otro grupo de notas, como en un acordeón diatónico.' },
      { title: 'Encuentra tu distribución.', text: 'Elige 28, 31 o 34 botones y tu afinación. Activa los nombres de las notas cuando quieras una referencia visual.' },
    ],
    tabletEye: 'MÁS ESPACIO PARA ENCONTRAR TU RITMO.', tabletTitle: ['En tu bolsillo.', 'O en una pantalla más grande.'],
    tabletText: 'Botones grandes que aprovechan la pantalla del teléfono. En iPad y tablets Android, elige tamaño y separación por separado según tu forma de tocar.',
    tabletAlt: 'Arenetto en iPad con una superficie de botones más amplia y el gabinete completo negro y dorado', tabletCaption: 'Teléfono y tablet. La misma identidad Arenetto.',
    labels: 'Nombres de notas opcionales', layouts: '28, 31 y 34 botones', tabletPresets: 'Tamaño y separación en tablets',
    sessionsEye: 'LA MÚSICA HABLA POR SÍ SOLA.', sessionsTitle: ['Más que una captura.', 'Una canción por tocar.'],
    sessionsText: 'Interpretaciones reales de Arenetto Accordion. Elige un video, sube el volumen y escucha el instrumento en acción.',
    playVideo: 'Ver', youtube: 'Ver en YouTube', socialInvite: '¿Estás tocando algo que te gusta? Compártelo con #arenetto.', socialHeading: 'Sigue la música',
    reviewEye: 'PALABRAS DE QUIENES LO TOCAN.', reviewTitle: ['Una pantalla pequeña.', 'Una conexión real.'],
    reviewText: 'Algunas palabras de quienes usan Arenetto, en App Store y Google Play.', original: 'Extracto original en español', translated: 'Traducción del español', reviewSource: 'Leer la reseña original', reviewDisclaimer: 'Extractos seleccionados de reseñas en App Store y Google Play. Se conserva el texto original en español. Son experiencias individuales, no una garantía.',
    privacyTitle: 'Solo tú y la música.', privacyItems: [['Sin anuncios', 'Nada que venderte mientras tocas.'], ['Sin cuenta', 'Abre la app y empieza a tocar.'], ['Tus ajustes son tuyos', 'Se guardan en tu dispositivo. La app no te rastrea.']],
    faqEye: 'ALGUNAS COSAS QUE VALE LA PENA SABER.', faqTitle: 'Antes de tu primera nota.',
    faq: [
      ['¿Arenetto es gratis?', 'Sí. Arenetto es gratis en App Store y Google Play, sin anuncios, suscripciones ni compras dentro de la app.'],
      ['¿Dónde puedo tocar?', 'En iPhone, iPad y teléfonos y tablets Android. El instrumento está diseñado para tocar en horizontal. Consulta la tienda para ver la compatibilidad actual con tu dispositivo.'],
      ['¿Cómo funciona el control de fuelle?', 'Un acordeón diatónico produce notas distintas al abrir o cerrar el fuelle. Arenetto te permite elegir la dirección mientras tocas los botones.'],
      ['¿Puedo elegir distribución y afinación?', 'Sí. Elige 28, 31 o 34 botones, tu familia de sonido y afinación, y muestra los nombres de las notas con sostenidos o bemoles si prefieres. En tablets también puedes ajustar tamaño y separación.'],
      ['¿Tengo que crear una cuenta?', 'No. No necesitas registrarte. Los ajustes del instrumento se guardan en tu dispositivo.'],
      ['¿Está disponible en español?', 'Sí. La app y este sitio están disponibles en español e inglés.'],
    ],
    help: '¿Necesitas una mano?', contact: 'Estamos para ayudarte.',
    closingEye: 'TU PRÓXIMA MELODÍA TE ESPERA.', closingTitle: ['Menos scroll.', 'Más música.'], closingText: 'Tu acordeón está a una descarga de distancia.',
    footerDescription: 'Un acordeón diatónico. Un poco más cerca de la música.', footerNav: 'Navegación del pie de página', footerLinks: ['Privacidad', 'Condiciones', 'Soporte'],
    iosLabel: 'Descarga Arenetto en App Store', androidLabel: 'Descarga Arenetto en Google Play',
    dialogClose: 'Cerrar video', dialogNotice: 'El video se carga desde YouTube solo cuando eliges verlo. Se aplica la política de privacidad de YouTube.', videoError: '¿No carga el reproductor? Mira este video directamente en YouTube.',
    downloadTitle: 'Tu próxima nota empieza aquí.', downloadText: 'Elige tu tienda y abre Arenetto en tu teléfono o tablet.', downloadEmbedded: 'Si tu app social no abre la tienda, usa su menú para abrir esta página en tu navegador.', androidStatus: 'Disponible en Google Play.',
    pageNames: {privacy: 'Privacidad', terms: 'Condiciones', support: 'Soporte'}, notFound: 'Una nota fuera de lugar.', notFoundText: 'Esta página no está aquí. Volvamos a la música.', home: 'Volver a Arenetto',
  },
};
